### ISSUE TITLE
Bread Kickstart release 0.4 Chapter 0 - Page 2

### ISSUE THREAD

**Issue by scottschram** [editorscut/ec012BakersKickstart#1]
1) Under Recommended Settings: “If you view this book in Apple's Books app, choose "Let lines break naturally" in Preferences > General.”

In Mac Books v4.2 there is no option for "Let lines break naturally" under General

![2022-03-08_17-56-55](https://user-images.githubusercontent.com/2750/157345906-6db9fc90-18bd-492e-8e4f-7719efbdc879.jpg)
.

However, there is an option to turn off Full Justification under Reading.  Maybe that's the new equivalent?
![2022-03-08_17-58-10](https://user-images.githubusercontent.com/2750/157346039-b202f46d-38c7-4522-b705-fb5e09cf2b5f.jpg)

2) The disclaimer is about code downloads and sample code.  Needs to be updated for a cookbook.  Unless you're going to include some code :)

**Comment by dimsumthinking** [comment]
1 is fixed. 2... I considered including excel formulas but you're right I won't and I'll remove this.

Thank you
